# Uncomment for profiling startup time (1/2)
# zmodload zsh/zprof
# setopt promptsubst
# typeset -F SECONDS

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Don't load ranger configs, they already exist in ~
export RANGER_LOAD_DEFAULT_RC=FALSE

# Statusline Setup
_prompt_statusline_left_segments=(status user machine git-branch directory)
_prompt_statusline_right_segments=(git-status history virtualenv clock)

# Configure bat
if (( ${+commands[bat]} )); then
  export BAT_THEME="Catppuccin Latte"
  export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"
  export HOMEBREW_BAT=1
fi

# Detect preferred GUI editor
if (( ${+commands[nova]} )); then
  export EDITOR='nova open --wait --no-recent'
  export VISUAL='nova open --wait --no-recent'
  alias nova='nova --no-recent'
fi

# Detect VS code terminal and change $EDITOR
if [[ "${TERM_PROGRAM}" == "vscode" ]]; then
  export EDITOR='code --wait'
  export VISUAL='code --wait'
fi


if [[ -e ${HOME}/.iterm2_shell_integration.zsh ]]; then
   source "${HOME}/.iterm2_shell_integration.zsh" || true
fi

if [[ -f ${HOME}/.docker/init-zsh.sh ]]; then
  source ${HOME}/.docker/init-zsh.sh || true
fi

# Set up aliases for eza
if (( ${+commands[eza]} )); then
  alias k='eza -l'
  alias ka='eza -l --git -a'
fi

# Disable python prompt modifications
export VIRTUAL_ENV_DISABLE_PROMPT=12
export PYENV_VIRTUALENV_DISABLE_PROMPT=12

#
# Fancy Colors
#

# Set variables that will be read by darken/brighten
# export BRIGHT_BAT='Solarized (light)'
# export BRIGHT_PROMPT='statusline -l'
# export BRIGHT_TERM='Solarized Light'
#
# export DARK_BAT='Solarized (dark)'
# export DARK_PROMPT='statusline -d'
# export DARK_TERM='Solarized Dark'

# Detect Dark mode and set it for the session
if is-darwin; then
  if [[ $(defaults read -g AppleInterfaceStyle 2&>/dev/null)  == 'Dark' ]]; then
    darken
  fi
fi

# Uncomment for profiling startup time (2/2)
# zprof
